/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#0040a1',
        'primary-container': '#0056d2',
        'on-primary': '#ffffff',
        'on-primary-container': '#ccd8ff',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b2c5ff',
        'secondary': '#48626e',
        'secondary-container': '#cbe7f5',
        'on-secondary': '#ffffff',
        'tertiary': '#822800',
        'tertiary-container': '#a93802',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ffb59b',
        'on-tertiary-container': '#ffcebd',
        'on-tertiary-fixed': '#380d00',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#191c1d',
        'on-surface-variant': '#424654',
        'outline': '#737785',
        'outline-variant': '#c3c6d6',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#b2c5ff',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        'editorial': '0 32px 64px rgba(25, 28, 29, 0.04)',
        'editorial-lg': '0 24px 48px rgba(0, 64, 161, 0.06)',
        'editorial-primary': '0 32px 64px rgba(0, 64, 161, 0.12)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out',
      },
    },
  },
  plugins: [],
};
