# Generated by Django 4.2.27 on 2026-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ('-completed_at', '-started_at')},
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='retake_limit',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of attempts a student is allowed.'),
        ),
    ]
